data_preprocessing:
  train_data_dir: 'data/frames/'
  test_data_dir: 'data/frames/'
  base_datagen: {rescale: !!python/float 0.00392156862745098, #or 1/255
                 validation_split: !!python/float 0.2}
  train_datagen: {rotation_range: 40,
                  horizontal_flip: True,
                  width_shift_range: 0.2,
                  height_shift_range: 0.2,
                  shear_range: 0.2,
                  zoom_range: 0.2}
  development_datagen: {}
  test_datagen: {}
  base_dataflow: {target_size: !!python/tuple [224,224],
                  batch_size: 32,
                  interpolation: 'bilinear'}
  train_dataflow: {subset: 'training',
                   shuffle: True}
  development_dataflow: {subset: 'validation',
                         shuffle: False}
  test_dataflow: {shuffle: False}

hub_layer_kwargs:
  tf_url: 'https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4'
  trainable: False
  optional: {input_shape: !!python/tuple [224,224,3]}

lst_tf_keras_layers:
  Dense(
  self.train_generator.num_classes,
  activation='softmax',
  kernel_regularizer=tf.keras.regularizers.l2(0.0001))

model.fit:
  epochs: 5

model_path: './models/'