model_name: 'ResNet50V2_0.2'
model_path: './models/'
model.fit:
  epochs: 5

data_preprocessing:
  train_data_dir: 'data/frames/train/'
  test_data_dir: 'data/frames/test/'
  train_base_datagen: {rescale: !!python/float 0.00392156862745098, # aka 1./255
                 validation_split: !!python/float 0.1}
  train_datagen: {rotation_range: 40,
                  horizontal_flip: True,
                  width_shift_range: !!python/float 0.2,
                  height_shift_range: !!python/float 0.2,
                  shear_range: !!python/float 0.2,
                  zoom_range: !!python/float 0.2,
                  brightness_range: [0.5,0.1],
                  }
  development_datagen: {}
  test_datagen: {rescale: !!python/float 0.00392156862745098,} # aka 1./255
  base_dataflow: {target_size: !!python/tuple [224,224],
                  interpolation: 'bilinear',
                  }
  train_dataflow: {subset: 'training',
                   shuffle: True,
                   batch_size: 32,
                  }
  development_dataflow: {
                      subset: 'validation',
                      shuffle: False,
                      batch_size: 32,
                    }
  test_dataflow: {shuffle: False,
                  batch_size: 1,
                  }

hub_layer_kwargs:
  tf_url: 'https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/4'
  trainable: False
  optional: {}

lst_tf_keras_layers: None

