model_name: 'ResNet50V2_0.1'
model_path: './models/'
model.fit:
  epochs: 2

data_preprocessing:
  train_data_dir: 'data/frames/train/'
  test_data_dir: 'data/frames/test/'
  train_base_datagen: {rescale: !!python/float 0.00392156862745098, # aka 1./255
                 validation_split: !!python/float 0.1}
  train_datagen: {}
  development_datagen: {}
  test_datagen: {rescale: !!python/float 0.00392156862745098,} # aka 1./255
  base_dataflow: {target_size: !!python/tuple [224,224],
                  interpolation: 'bilinear',
                  seed: 11828331}
  train_dataflow: {subset: 'training',
                   shuffle: True,
                   batch_size: 32,
                  }
  development_dataflow: {
                      subset: 'validation',
                      shuffle: False,
                      batch_size: 32,
                    }
  test_dataflow: {shuffle: False,
                  batch_size: 1,
                  }

hub_layer_kwargs:
  tf_url: 'https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/4'
  trainable: False
  optional: {}

lst_tf_keras_layers:
  Dense(
  self.train_generator.num_classes,
  activation='softmax',
  kernel_regularizer=tf.keras.regularizers.l2(0.0001))

